name: koyag_qr
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Inicio
  provider: 2.0.1

  #Data
  shared_preferences: ^0.5.4+3

  #IMAGEN
  native_color: 1.1.0

  #UTILS
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: roboto
      fonts:
        - asset: assets/Roboto.ttf
          style: normal